title: Paige Aldenberg # your name (or website title) here
logo: "/images/Penguin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student in Biological and Environmental Sciences 
  <br><br>
  Department of Geoscience
  <br><br>
  <a href="https://www.linkedin.com/in/paige-a-b260ab1b4/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
